### PR TITLE
Add support for preserving case

### PR DESCRIPTION
**Pull request by eatonphil**
Hi! I'd like to be able to preserve the case of the identifiers used. This seemed like the simplest way to go about doing so. Any thoughts?

### CODE REVIEW

**Comment by eatonphil** [comment]
I've broken case insensitivity of operators in this PR. I think I'll need to break out the utility functions to differentiate between identifiers and operators.

**Comment by eatonphil** [comment]
@nwronski is there anything I can do to get this merged?

**Comment by nwronski** [comment]
It is not documented in the README, but there is an optional second argument for the parser to provide an options object. How would you feel about making this an option in that options object? We could then control this option using a flag provided to the command line version. Options passed in as the second argument to the `parse()` function  should be available as a global var named `options` within the grammar file.

**Comment by eatonphil** [comment]
That sounds great! Will fix.

**Comment by eatonphil** [comment]
@nwronski sorry for the delay. I replaced the global variable with a new config option and updated documentation.

How does this look?

**Comment by eatonphil** [comment]
@nwronski is there anything I can do to get this merged?

**Comment by eatonphil** [comment]
@nwronski hey! is there anything i can do to get this merged?

**Comment by nwronski** [comment]
Sorry, this project is in a bit of a limbo state as Code School was shut down and I'm no longer on the team that made use of this module. I had some time to research this issue, and it looks like sqlite, contrary to most other flavors of SQL, does not preserve case sensitivity in identifiers, even when they are quoted. So, technically, I should be fixing this parser so that it lowercases quoted identifiers, as well as unquoted identifiers. That probably isn't the news you want to hear after waiting all this time, but all hope is not lost. I am leaning towards fixing the behavior here, in the way I've just described, but also exposing a new property in identifier nodes for the raw, unprocessed form that an identifier was written in the input SQL. So, instead of needing to toggle an option to change the behavior of the parser, you could choose which format you would like to use (lowercased or unmodified from input).

**Comment by eatonphil** [comment]
Thanks for the update. Closing

**Pull request closed without merging**
